backend:
  name: github
  repo: Night-Vision-Discord/website
  branch: main
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
    openAuthoring: '{{message}}'
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: posts
    folder: "posts"
    create: true
    extension: "md"
    slug: "{{slug}}"

